
<p> Etes vous sur de vouloir supprimer ce client: 
    ' <?php echo $this->numcli; ?>'? 
</p>

<form action="<?php echo $this->url(array('controller' =>'client', 'action'=>'supprimer')); ?>" method="post">
    <div>
        <input type="hidden" name="NUM_CLI" value="<?php echo $this->numcli; ?>" />
        <input type="submit" name="supprimer" value="oui"/>
        <input type="submit" name="supprimer" value="non"/>
    </div>
</form>
